version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgresql_container
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: secret
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data  # Define el volumen "data" aquí

volumes:
  data:  # Define el volumen "data" aquí
